AWSTemplateFormatVersion: '2010-09-09'
Description: Apache Airflow Master Stack

Parameters:
  EnvType:
    Description: Environment type (prod/staging)
    Type: String
    Default: prod
  DBPassword:
    NoEcho: true
    Description: RDS master password
    Type: String
    MinLength: 8
  AirflowImage:
    Description: ECR image URI for Airflow
    Type: String
    Default: your-ecr-repo/airflow:latest

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
      Parameters:
        EnvType: !Ref EnvType

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: rds.yaml
      Parameters:
        VPCStack: !GetAtt VPCStack.Outputs.VPCId
        SubnetIds: !Join [',', !GetAtt VPCStack.Outputs.PrivateSubnets]
        DBPassword: !Ref DBPassword

  RedisStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: redis.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        SubnetIds: !Join [',', !GetAtt VPCStack.Outputs.PrivateSubnets]

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: s3.yaml

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ecs.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        SubnetIds: !Join [',', !GetAtt VPCStack.Outputs.PublicSubnets]
        AirflowImage: !Ref AirflowImage
        RDSEndpoint: !GetAtt RDSStack.Outputs.RDSEndpoint
        RedisEndpoint: !GetAtt RedisStack.Outputs.RedisEndpoint

Outputs:
  AirflowWebURL:
    Value: !GetAtt ECSStack.Outputs.ALBDNSName
  RDSEndpoint:
    Value: !GetAtt RDSStack.Outputs.RDSEndpoint
