AWSTemplateFormatVersion: '2010-09-09'
Description: RDS Database for Apache Airflow Metadata

Resources:
  AirflowDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Airflow RDS instance
      SubnetIds:
        - subnet-0c7e672ca98f567d8
        - subnet-0a55d951c62449f70

  AirflowRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: airflow-metadata-db
      AllocatedStorage: 20
      DBInstanceClass: db.t4g.micro  # Free-tier eligible instance type
      Engine: postgres
      EngineVersion: 15.12
      MasterUsername: airflowadmin
      MasterUserPassword: airflowpassword  # Replace with a secure password
      DBSubnetGroupName: !Ref AirflowDBSubnetGroup
      VPCSecurityGroups:
        - sg-03dd3c168a2e2f943
      BackupRetentionPeriod: 7
      MultiAZ: false
      PubliclyAccessible: false

Outputs:
  RDSInstanceEndpoint:
    Value: !GetAtt AirflowRDSInstance.Endpoint.Address
    Export:
      Name: AirflowRDSInstanceEndpoint

  RDSInstanceArn:
    Value: !Ref AirflowRDSInstance
    Export:
      Name: AirflowRDSInstanceIdentifier